### ISSUE TITLE
大概什么时候能找到捏？如果丢了可以说一声嗷

### ISSUE THREAD

**Issue by 1da1da** [whuzjw/ycy#1]
rt，感谢

**Comment by whuzjw** [comment]
这是我从本地电脑上弄的, 云端的没了, 运行a2_mpxxx.py, 或者ycy文件夹里的a2_mpxxx.py啥的, 环境啥的自己试试, 反正代码肯定能运行通

**Comment by 1da1da** [comment]
你还记得这几个不同的文件（比如ubuntu/ubuntu_test/text/firebox）有什么区别吗，你之前是运行哪个捏？还是你也不记得了，我自己一个个试一下

**Comment by whuzjw** [comment]
一般只用过a2_mp.py和a2_mp_ubuntu.py就行, ubuntu是我在服务器上运行的, 虽然和本地存的代码有区别, 但可以借鉴, mp是多进程的意思
关于验证, 你可以不开headless模式, 就是注释掉headless那一行, 然后改成单进程, 会蹦出来浏览器, 可以看他是不是成功, 然后再加上headless, 看看截图成不成功, 成功就行了

**Comment by junwuzhang19** [comment]
可能涉及一些mg信息, 所以如果没什么问题我把这个仓库删了

**Comment by 1da1da** [comment]
好的，谢谢，可以删啦
